name: 'Nightly'

on:
  schedule:
    - cron: '15 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    # Which branches to build nightlies for?
    strategy:
      matrix:
        branch: [ "master", "forge/master" ]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
      # Somewhat complex: Figure out which version number to use as the base
      # We use the last release we built on this branch
      - name: Determine last release from this branch
      - uses: actions/github-script@v6
        id: nightly-info
        with:
          script: |
            const script = require('./.github/nightly_version.mjs');
            await script({github, context, core});
      - name: Get result
        run: |
          echo "${{steps.nightly-info.outputs.version}}"
          echo "${{steps.nightly-info.outputs.release_version}}"
          echo "${{steps.nightly-info.outputs.release_notes}}"
#      - name: Set up JDK 17
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Generate assets
#        run: ./gradlew runData build
#      - uses: actions/upload-artifact@v2
#        with:
#          name: dist
#          path: build/libs/
